# Generated by Django 3.2.7 on 2021-09-26 18:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_repository_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='picture',
        ),
        migrations.AddField(
            model_name='image',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='image',
            name='creator',
            field=models.CharField(default='unkown', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
