# Generated by Django 3.2.7 on 2021-09-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_repository_app', '0002_auto_20210926_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='created_on',
            new_name='uploaded',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('images', models.ManyToManyField(to='image_repository_app.Image')),
            ],
        ),
    ]
